# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [2]:
chipo = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv',delimiter='\t',low_memory=False)

### Step 4. How many products cost more than $10.00?

In [27]:
chipo_float = chipo

chipo_float['float_item_price'] = chipo.item_price.apply(lambda x : x.replace('$','')).astype(float)

chipo_float_filtered = chipo_float[chipo_float.quantity==1]

chipo_float_filtered[chipo_float_filtered.float_item_price >10.00]['item_name'].value_counts().count()

25

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [38]:
chipo_filtered = chipo_float.drop_duplicates(['item_name','quantity'])
chipo_one_prod = chipo_filtered[chipo_filtered.quantity == 1]

chipo_one_prod.groupby(by=['item_name','item_price']).sum().sort_values(by=['float_item_price'])

,,order_id,quantity,float_item_price
item_name,item_price,,,
Bottled Water,$1.09,17,1,1.09
Canned Soda,$1.09,14,1,1.09
Canned Soft Drink,$1.25,114,1,1.25
Side of Chips,$1.69,3,1,1.69
Chips,$2.15,19,1,2.15
Chips and Fresh Tomato Salsa,$2.39,1,1,2.39
Chips and Tomatillo-Red Chili Salsa,$2.39,130,1,2.39
Chips and Tomatillo-Green Chili Salsa,$2.39,1,1,2.39
Chips and Roasted Chili-Corn Salsa,$2.39,85,1,2.39
Chips and Tomatillo Red Chili Salsa,$2.95,49,1,2.95
Chips and Tomatillo Green Chili Salsa,$2.95,18,1,2.95
Chips and Roasted Chili Corn Salsa,$2.95,102,1,2.95
Chips and Mild Fresh Tomato Salsa,$3.00,279,1,3.00
Nantucket Nectar,$3.39,1,1,3.39
Izze,$3.39,1,1,3.39
Chips and Guacamole,$4.45,5,1,4.45
6 Pack Soft Drink,$6.49,129,1,6.49
Crispy Tacos,$7.40,217,1,7.40
Bowl,$7.40,279,1,7.40
Salad,$7.40,575,1,7.40
Burrito,$7.40,214,1,7.40
Chicken Burrito,$8.49,8,1,8.49
Veggie Salad,$8.49,686,1,8.49
Veggie Crispy Tacos,$8.49,668,1,8.49
Chicken Crispy Tacos,$8.75,6,1,8.75
Chicken Salad Bowl,$8.75,20,1,8.75
Chicken Soft Tacos,$8.75,6,1,8.75
Barbacoa Burrito,$8.99,11,1,8.99
Steak Salad,$8.99,276,1,8.99
Carnitas Burrito,$8.99,14,1,8.99
Carnitas Salad,$8.99,1500,1,8.99
Carnitas Bowl,$8.99,17,1,8.99
Steak Bowl,$8.99,25,1,8.99
Carnitas Crispy Tacos,$9.25,230,1,9.25
Barbacoa Soft Tacos,$9.25,26,1,9.25
Carnitas Soft Tacos,$9.25,103,1,9.25
Steak Crispy Tacos,$9.25,40,1,9.25
Steak Soft Tacos,$9.25,4,1,9.25
Chicken Bowl,$10.98,3,1,10.98
Chicken Salad,$10.98,109,1,10.98
Veggie Salad Bowl,$11.25,83,1,11.25
Veggie Bowl,$11.25,28,1,11.25
Veggie Burrito,$11.25,26,1,11.25
Veggie Soft Tacos,$11.25,304,1,11.25
Steak Burrito,$11.75,4,1,11.75
Barbacoa Crispy Tacos,$11.75,75,1,11.75
Barbacoa Bowl,$11.75,19,1,11.75
Barbacoa Salad Bowl,$11.89,501,1,11.89
Steak Salad Bowl,$11.89,250,1,11.89
Carnitas Salad Bowl,$11.89,468,1,11.89

Solução dada:

### Step 6. Sort by the name of the item

In [39]:
chipo.sort_values(by=['item_name'])

,order_id,quantity,item_name,choice_description,item_price,float_item_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],$12.98,12.98
341,148,1,6 Pack Soft Drink,[Diet Coke],$6.49,6.49
1849,749,1,6 Pack Soft Drink,[Coke],$6.49,6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],$6.49,6.49
2713,1076,1,6 Pack Soft Drink,[Coke],$6.49,6.49
...,...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75,8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",$8.75,8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",$8.49,8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25,11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",$8.49,8.49

### Step 7. What was the quantity of the most expensive item ordered?

In [51]:
# the most expesive itens are Barbacoa Salad Bowl,	Steak Salad Bowl,	Carnitas Salad Bowl	

for item in ['Barbacoa Salad Bowl',	'Steak Salad Bowl',	'Carnitas Salad Bowl']:
    print(item,'was ordered ', chipo[chipo.item_name == item].quantity.sum(),end=' times.\n')

Barbacoa Salad Bowl was ordered  10 times.
Steak Salad Bowl was ordered  31 times.
Carnitas Salad Bowl was ordered  6 times.

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [56]:
chipo[chipo.item_name == 'Veggie Salad Bowl'].order_id.value_counts().count()

18

### Step 9. How many times did someone order more than one Canned Soda?

In [60]:
chipo[(chipo.item_name == 'Canned Soda') & (chipo.quantity >=2)]#.order_id.value_counts().count()

,order_id,quantity,item_name,choice_description,item_price,float_item_price
18,9,2,Canned Soda,[Sprite],$2.18,2.18
51,23,2,Canned Soda,[Mountain Dew],$2.18,2.18
162,73,2,Canned Soda,[Diet Coke],$2.18,2.18
171,76,2,Canned Soda,[Diet Dr. Pepper],$2.18,2.18
350,150,2,Canned Soda,[Diet Coke],$2.18,2.18
352,151,2,Canned Soda,[Coca Cola],$2.18,2.18
698,287,2,Canned Soda,[Coca Cola],$2.18,2.18
700,288,2,Canned Soda,[Coca Cola],$2.18,2.18
909,376,2,Canned Soda,[Mountain Dew],$2.18,2.18
1091,450,2,Canned Soda,[Dr. Pepper],$2.18,2.18
1092,450,2,Canned Soda,[Coca Cola],$2.18,2.18
1944,787,2,Canned Soda,[Dr. Pepper],$2.18,2.18
2135,859,2,Canned Soda,[Diet Coke],$2.18,2.18
2235,901,4,Canned Soda,[Sprite],$4.36,4.36
2905,1156,2,Canned Soda,[Coca Cola],$2.18,2.18
2906,1156,2,Canned Soda,[Sprite],$2.18,2.18
3152,1258,2,Canned Soda,[Dr. Pepper],$2.18,2.18
3364,1349,2,Canned Soda,[Coca Cola],$2.18,2.18
3592,1440,2,Canned Soda,[Diet Coke],$2.18,2.18
3866,1550,2,Canned Soda,[Mountain Dew],$2.18,2.18

The problem here is the question. How many orders were made? or How much quantity was purchased.